name: Tag and Release on Push to Master

on:
  push:
    branches:
      - master

jobs:
  tag-and-release:
    name: Tag and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Tag Creation
        uses: matthieuEv/Github-Action-Tag@v1 #커밋메시지 패턴에 따라 태그 생성
        id: tag-creation

      - name: Debug - Output the generated tag and commit info
        run: |
          echo "Make Release: ${{ steps.tag-creation.outputs.makeRelease }}"
          echo "Commit Name: ${{ steps.tag-creation.outputs.commitName }}"
          echo "New Version: ${{ steps.tag-creation.outputs.newVersion }}"

      - name: Set up JDK 17
        if: steps.tag-creation.outputs.makeRelease == 'true'
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Create GitHub Release
        if: steps.tag-creation.outputs.makeRelease == 'true' #새로운 태그가 생성되었을 때 실행. 생성된 태그이름으로 릴리즈 생성
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.tag-creation.outputs.newVersion }} # 이전 단계에서 생성된 새버전의 태그 이름을 사용하여 릴리즈 생성
          release_name: Release ${{ steps.tag-creation.outputs.newVersion }} # 릴리즈의 이름을 태그 이름 포함하여 자동으로 설명 추가
          body: "Automated release for version ${{ steps.tag-creation.outputs.newVersion }}" # 릴리즈 본문에 태그 이름 포함하여 자동 설명 추가
          draft: false # 릴리즈 바로 게시
          prerelease: false #pre릴리즈 생성 안함
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
